### ISSUE TITLE
run_stats

### ISSUE THREAD

**Issue by Michael971022** [shashankkotyan/DualQualityAssessment#2]
step.5 Calculate the statstics for the attacks.
python -u code/run_stats.py > run_stats.txt

I found that there is no run_stats.py in the dir?

**Comment by shashankkotyan** [comment]
Hi, thanks for pointing this out. 

I acknowledge that I haven't added the `run_stats.py`, file.
As I am currently analysing the attacks with the current attacks, at the moment I didnot include the file. 


I have updated the Readme file.
